import type { Config } from "tailwindcss";
import tailwindcssRtl from "tailwindcss-rtl";

const config: Config = {
  darkMode: ["class", ".dark"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      tablet: "1181px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      fontFamily: {
        sans: ["var(--font-lato)", "system-ui", "sans-serif"],
        hebrew: ["var(--font-rubik)", "system-ui", "sans-serif"],
      },
      padding: {
        xxs: "var(--spacing-xxs)",
        xs: "var(--spacing-xs)",
        sm: "var(--spacing-sm)",
        md: "var(--spacing-md)",
        lg: "var(--spacing-lg)",
        xl: "var(--spacing-xl)",
        xxl: "var(--spacing-xxl)",
        "3xl": "var(--spacing-3xl)",
        "4xl": "var(--spacing-4xl)",
        "5xl": "var(--spacing-5xl)",
        "6xl": "var(--spacing-6xl)",
        "7xl": "var(--spacing-7xl)",
        "8xl": "var(--spacing-8xl)",
      },
      margin: {
        xxs: "var(--spacing-xxs)",
        xs: "var(--spacing-xs)",
        sm: "var(--spacing-sm)",
        md: "var(--spacing-md)",
        lg: "var(--spacing-lg)",
        xl: "var(--spacing-xl)",
        xxl: "var(--spacing-xxl)",
        "3xl": "var(--spacing-3xl)",
        "4xl": "var(--spacing-4xl)",
        "5xl": "var(--spacing-5xl)",
        "6xl": "var(--spacing-6xl)",
        "7xl": "var(--spacing-7xl)",
        "8xl": "var(--spacing-8xl)",
      },
      gap: {
        xxs: "var(--spacing-xxs)",
        xs: "var(--spacing-xs)",
        sm: "var(--spacing-sm)",
        md: "var(--spacing-md)",
        lg: "var(--spacing-lg)",
        xl: "var(--spacing-xl)",
        xxl: "var(--spacing-xxl)",
        "3xl": "var(--spacing-3xl)",
        "4xl": "var(--spacing-4xl)",
        "5xl": "var(--spacing-5xl)",
        "6xl": "var(--spacing-6xl)",
        "7xl": "var(--spacing-7xl)",
        "8xl": "var(--spacing-8xl)",
      },
      spacing: {
        xxs: "var(--spacing-xxs)",
        xs: "var(--spacing-xs)",
        sm: "var(--spacing-sm)",
        md: "var(--spacing-md)",
        lg: "var(--spacing-lg)",
        xl: "var(--spacing-xl)",
        xxl: "var(--spacing-xxl)",
        "3xl": "var(--spacing-3xl)",
        "4xl": "var(--spacing-4xl)",
        "5xl": "var(--spacing-5xl)",
        "6xl": "var(--spacing-6xl)",
        "7xl": "var(--spacing-7xl)",
        "8xl": "var(--spacing-8xl)",
      },
      width: {
        xxs: "var(--sizing-xxs)",
        xs: "var(--sizing-xs)",
        sm: "var(--sizing-sm)",
        md: "var(--sizing-md)",
        lg: "var(--sizing-lg)",
        xl: "var(--sizing-xl)",
        xxl: "var(--sizing-xxl)",
        "3xl": "var(--sizing-3xl)",
        "4xl": "var(--sizing-4xl)",
        "5xl": "var(--sizing-5xl)",
        "6xl": "var(--sizing-6xl)",
        "7xl": "var(--sizing-7xl)",
        "8xl": "var(--sizing-8xl)",
        "9xl": "var(--sizing-9xl)",
        "10xl": "var(--sizing-10xl)",
        "11xl": "var(--sizing-11xl)",
      },
      height: {
        xxs: "var(--sizing-xxs)",
        xs: "var(--sizing-xs)",
        sm: "var(--sizing-sm)",
        md: "var(--sizing-md)",
        lg: "var(--sizing-lg)",
        xl: "var(--sizing-xl)",
        xxl: "var(--sizing-xxl)",
        "3xl": "var(--sizing-3xl)",
        "4xl": "var(--sizing-4xl)",
        "5xl": "var(--sizing-5xl)",
        "6xl": "var(--sizing-6xl)",
        "7xl": "var(--sizing-7xl)",
        "8xl": "var(--sizing-8xl)",
        "9xl": "var(--sizing-9xl)",
        "10xl": "var(--sizing-10xl)",
        "11xl": "var(--sizing-11xl)",
      },
      size: {
        xxs: "var(--sizing-xxs)",
        xs: "var(--sizing-xs)",
        sm: "var(--sizing-sm)",
        md: "var(--sizing-md)",
        lg: "var(--sizing-lg)",
        xl: "var(--sizing-xl)",
        xxl: "var(--sizing-xxl)",
        "3xl": "var(--sizing-3xl)",
        "4xl": "var(--sizing-4xl)",
        "5xl": "var(--sizing-5xl)",
        "6xl": "var(--sizing-6xl)",
        "7xl": "var(--sizing-7xl)",
        "8xl": "var(--sizing-8xl)",
        "9xl": "var(--sizing-9xl)",
        "10xl": "var(--sizing-10xl)",
        "11xl": "var(--sizing-11xl)",
      },
      borderRadius: {
        "3xs": "var(--radius-3xs)",
        xxs: "var(--radius-xxs)",
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        xxl: "var(--radius-xxl)",
      },
      colors: {
        surface: {
          primary: "var(--surface-primary)",
          secondary: "var(--surface-secondary)",
          "plus-1": "var(--surface-plus-1)",
          "plus-2": "var(--surface-plus-2)",
          "plus-3": "var(--surface-plus-3)",
          "plus-4": "var(--surface-plus-4)",
          "plus-6": "var(--surface-plus-6)",
          "plus-7": "var(--surface-plus-7)",
          invert: "var(--surface-invert)",
          "invert-10": "var(--surface-invert-10)",
          "blue-primary": "var(--surface-blue-primary)",
          "blue-plus-1": "var(--surface-blue-plus-1)",
          "blue-minus-5": "var(--surface-blue-minus-5)",
          "green-primary": "var(--surface-green-primary)",
          "green-plus-1": "var(--surface-green-plus-1)",
          "amber-primary": "var(--surface-amber-primary)",
          "amber-plus-1": "var(--surface-amber-plus-1)",
          "rose-primary": "var(--surface-rose-primary)",
          "rose-plus-1": "var(--surface-rose-plus-1)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          "plus-7": "var(--text-plus-7)",
          "minus-1": "var(--text-minus-1)",
          "minus-2": "var(--text-minus-2)",
          invert: "var(--text-invert)",
          "blue-primary": "var(--text-blue-primary)",
          "green-primary": "var(--text-green-primary)",
          "amber-primary": "var(--text-amber-primary)",
          "rose-primary": "var(--text-rose-primary)",
        },
        border: {
          primary: "var(--border-primary)",
          secondary: "var(--border-secondary)",
          "plus-1": "var(--border-plus-1)",
          "plus-2": "var(--border-plus-2)",
          "plus-3": "var(--border-plus-3)",
          "blue-primary": "var(--border-blue-primary)",
          "blue-minus-4": "var(--border-blue-minus-4)",
          "rose-primary": "var(--border-rose-primary)",
        },
        outline: {
          primary: "var(--outline-primary)",
          secondary: "var(--outline-secondary)",
          "plus-2": "var(--outline-plus-2)",
          "plus-3": "var(--outline-plus-3)",
          "blue-primary": "var(--outline-blue-primary)",
          "blue-minus-4": "var(--outline-blue-minus-4)",
          "rose-primary": "var(--outline-rose-primary)",
        },
      },
      boxShadow: {
        "elevation-1": "0px 2px 6px rgba(0, 0, 0, 0.48)",
        "elevation-1-left": "-2px 0px 6px rgba(0, 0, 0, 0.48)",
        "elevation-2": "0px 4px 6px rgba(0, 0, 0, 0.48)",
        "elevation-2-left": "-4px 0px 6px rgba(0, 0, 0, 0.48)",
        "elevation-3": "0px 2px 6px rgba(0, 0, 0, 0.48), 0px 4px 8px rgba(0, 0, 0, 0.48)",
        "elevation-4": "0px 4px 8px rgba(0, 0, 0, 0.52), 0px 6px 12px rgba(0, 0, 0, 0.42)",
        "elevation-5": "0px 4px 8px rgba(0, 0, 0, 0.56), 0px 6px 8px rgba(0, 0, 0, 0.48), 0px 8px 16px rgba(0, 0, 0, 0.36)",
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-in-out",
        "fade-out": "fadeOut 0.3s ease-in-out",
        "slide-up": "slideUp 0.4s ease-out",
        "slide-down": "slideDown 0.4s ease-out",
        "scale-in": "scaleIn 0.2s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        fadeOut: {
          "0%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
    },
  },
  plugins: [tailwindcssRtl],
};

export default config;
